<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = $this->getCountries();

        foreach ($countries as $country) {
            Country::query()->updateOrCreate([
                'code' => $country['code']
            ], [
                'name' => $country['name'],
                'local_name' => $country['local_name'],
                'is_free' => $country['code'] == 'AF',
                'is_active' => in_array($country['code'], ['AF', 'US']),
            ]);
        }
    }


    protected function getCountries()
    {
        return [
            ["code" => "AD", "name" => "Andorra", "local_name" => "Andorra"],
            ["code" => "AE", "name" => "United Arab Emirates", "local_name" => "دولة الإمارات العربية المتحدة"],
            ["code" => "AF", "name" => "Afghanistan", "local_name" => "افغانستان"],
            ["code" => "AG", "name" => "Antigua and Barbuda", "local_name" => "Antigua and Barbuda"],
            ["code" => "AI", "name" => "Anguilla", "local_name" => "Anguilla"],
            ["code" => "AL", "name" => "Albania", "local_name" => "Shqipëria"],
            ["code" => "AM", "name" => "Armenia", "local_name" => "Հայաստան"],
            ["code" => "AO", "name" => "Angola", "local_name" => "Angola"],
            ["code" => "AQ", "name" => "Antarctica", "local_name" => "Antarctica"],
            ["code" => "AR", "name" => "Argentina", "local_name" => "Argentina"],
            ["code" => "AS", "name" => "American Samoa", "local_name" => "American Samoa"],
            ["code" => "AT", "name" => "Austria", "local_name" => "Österreich"],
            ["code" => "AU", "name" => "Australia", "local_name" => "Australia"],
            ["code" => "AW", "name" => "Aruba", "local_name" => "Aruba"],
            ["code" => "AX", "name" => "Åland Islands", "local_name" => "Åland"],
            ["code" => "AZ", "name" => "Azerbaijan", "local_name" => "Azərbaycan"],
            ["code" => "BA", "name" => "Bosnia and Herzegovina", "local_name" => "Bosna i Hercegovina"],
            ["code" => "BB", "name" => "Barbados", "local_name" => "Barbados"],
            ["code" => "BD", "name" => "Bangladesh", "local_name" => "বাংলাদেশ"],
            ["code" => "BE", "name" => "Belgium", "local_name" => "België"],
            ["code" => "BF", "name" => "Burkina Faso", "local_name" => "Burkina Faso"],
            ["code" => "BG", "name" => "Bulgaria", "local_name" => "България"],
            ["code" => "BH", "name" => "Bahrain", "local_name" => "‏البحرين"],
            ["code" => "BI", "name" => "Burundi", "local_name" => "Burundi"],
            ["code" => "BJ", "name" => "Benin", "local_name" => "Bénin"],
            ["code" => "BL", "name" => "Saint Barthélemy", "local_name" => "Saint-Barthélemy"],
            ["code" => "BM", "name" => "Bermuda", "local_name" => "Bermuda"],
            ["code" => "BN", "name" => "Brunei", "local_name" => "Negara Brunei Darussalam"],
            ["code" => "BO", "name" => "Bolivia", "local_name" => "Bolivia"],
            ["code" => "BQ", "name" => "Bonaire", "local_name" => "Caribisch Nederland"],
            ["code" => "BR", "name" => "Brazil", "local_name" => "Brasil"],
            ["code" => "BS", "name" => "Bahamas", "local_name" => "Bahamas"],
            ["code" => "BT", "name" => "Bhutan", "local_name" => "ʼbrug-yul"],
            ["code" => "BV", "name" => "Bouvet Island", "local_name" => "Bouvetøya"],
            ["code" => "BW", "name" => "Botswana", "local_name" => "Botswana"],
            ["code" => "BY", "name" => "Belarus", "local_name" => "Беларусь"],
            ["code" => "BZ", "name" => "Belize", "local_name" => "Belize"],
            ["code" => "CA", "name" => "Canada", "local_name" => "Canada"],
            ["code" => "CC", "name" => "Cocos (Keeling) Islands", "local_name" => "Cocos (Keeling) Islands"],
            ["code" => "CD", "name" => "Democratic Republic of the Congo", "local_name" => "Jamhuri ya Kidemokrasia ya Kongo"],
            ["code" => "CF", "name" => "Central African Republic", "local_name" => "République centrafricaine"],
            ["code" => "CG", "name" => "Republic of the Congo", "local_name" => "République du Congo"],
            ["code" => "CH", "name" => "Switzerland", "local_name" => "Schweiz"],
            ["code" => "CI", "name" => "Ivory Coast", "local_name" => "Côte d'Ivoire"],
            ["code" => "CK", "name" => "Cook Islands", "local_name" => "Cook Islands"],
            ["code" => "CL", "name" => "Chile", "local_name" => "Chile"],
            ["code" => "CM", "name" => "Cameroon", "local_name" => "Cameroon"],
            ["code" => "CN", "name" => "China", "local_name" => "中国"],
            ["code" => "CO", "name" => "Colombia", "local_name" => "Colombia"],
            ["code" => "CR", "name" => "Costa Rica", "local_name" => "Costa Rica"],
            ["code" => "CU", "name" => "Cuba", "local_name" => "Cuba"],
            ["code" => "CV", "name" => "Cape Verde", "local_name" => "Cabo Verde"],
            ["code" => "CW", "name" => "Curaçao", "local_name" => "Curaçao"],
            ["code" => "CX", "name" => "Christmas Island", "local_name" => "Christmas Island"],
            ["code" => "CY", "name" => "Cyprus", "local_name" => "Κύπρος"],
            ["code" => "CZ", "name" => "Czech Republic", "local_name" => "Česká republika"],
            ["code" => "DE", "name" => "Germany", "local_name" => "Deutschland"],
            ["code" => "DJ", "name" => "Djibouti", "local_name" => "Djibouti"],
            ["code" => "DK", "name" => "Denmark", "local_name" => "Danmark"],
            ["code" => "DM", "name" => "Dominica", "local_name" => "Dominica"],
            ["code" => "DO", "name" => "Dominican Republic", "local_name" => "República Dominicana"],
            ["code" => "DZ", "name" => "Algeria", "local_name" => "الجزائر"],
            ["code" => "EC", "name" => "Ecuador", "local_name" => "Ecuador"],
            ["code" => "EE", "name" => "Estonia", "local_name" => "Eesti"],
            ["code" => "EG", "name" => "Egypt", "local_name" => "مصر"],
            ["code" => "EH", "name" => "Western Sahara", "local_name" => "الصحراء الغربية"],
            ["code" => "ER", "name" => "Eritrea", "local_name" => "ኤርትራ"],
            ["code" => "ES", "name" => "Spain", "local_name" => "España"],
            ["code" => "ET", "name" => "Ethiopia", "local_name" => "ኢትዮጵያ"],
            ["code" => "FI", "name" => "Finland", "local_name" => "Suomi"],
            ["code" => "FJ", "name" => "Fiji", "local_name" => "Fiji"],
            ["code" => "FK", "name" => "Falkland Islands", "local_name" => "Falkland Islands"],
            ["code" => "FM", "name" => "Micronesia", "local_name" => "Micronesia"],
            ["code" => "FO", "name" => "Faroe Islands", "local_name" => "Føroyar"],
            ["code" => "FR", "name" => "France", "local_name" => "France"],
            ["code" => "GA", "name" => "Gabon", "local_name" => "Gabon"],
            ["code" => "GB", "name" => "United Kingdom", "local_name" => "United Kingdom"],
            ["code" => "GD", "name" => "Grenada", "local_name" => "Grenada"],
            ["code" => "GE", "name" => "Georgia", "local_name" => "საქართველო"],
            ["code" => "GF", "name" => "French Guiana", "local_name" => "Guyane française"],
            ["code" => "GG", "name" => "Guernsey", "local_name" => "Guernsey"],
            ["code" => "GH", "name" => "Ghana", "local_name" => "Ghana"],
            ["code" => "GI", "name" => "Gibraltar", "local_name" => "Gibraltar"],
            ["code" => "GL", "name" => "Greenland", "local_name" => "Kalaallit Nunaat"],
            ["code" => "GM", "name" => "Gambia", "local_name" => "Gambia"],
            ["code" => "GN", "name" => "Guinea", "local_name" => "Guinée"],
            ["code" => "GP", "name" => "Guadeloupe", "local_name" => "Guadeloupe"],
            ["code" => "GQ", "name" => "Equatorial Guinea", "local_name" => "Guinea Ecuatorial"],
            ["code" => "GR", "name" => "Greece", "local_name" => "Ελλάδα"],
            ["code" => "GS", "name" => "South Georgia and the South Sandwich Islands", "local_name" => "South Georgia and the South Sandwich Islands"],
            ["code" => "GT", "name" => "Guatemala", "local_name" => "Guatemala"],
            ["code" => "GU", "name" => "Guam", "local_name" => "Guam"],
            ["code" => "GW", "name" => "Guinea-Bissau", "local_name" => "Guiné-Bissau"],
            ["code" => "GY", "name" => "Guyana", "local_name" => "Guyana"],
            ["code" => "HK", "name" => "Hong Kong", "local_name" => "香港"],
            ["code" => "HM", "name" => "Heard Island and McDonald Islands", "local_name" => "Heard Island and McDonald Islands"],
            ["code" => "HN", "name" => "Honduras", "local_name" => "Honduras"],
            ["code" => "HR", "name" => "Croatia", "local_name" => "Hrvatska"],
            ["code" => "HT", "name" => "Haiti", "local_name" => "Haïti"],
            ["code" => "HU", "name" => "Hungary", "local_name" => "Magyarország"],
            ["code" => "ID", "name" => "Indonesia", "local_name" => "Indonesia"],
            ["code" => "IE", "name" => "Ireland", "local_name" => "Éire"],
            ["code" => "IL", "name" => "Israel", "local_name" => "‏ישראל"],
            ["code" => "IM", "name" => "Isle of Man", "local_name" => "Isle of Man"],
            ["code" => "IN", "name" => "India", "local_name" => "India"],
            ["code" => "IO", "name" => "British Indian Ocean Territory", "local_name" => "British Indian Ocean Territory"],
            ["code" => "IQ", "name" => "Iraq", "local_name" => "‏العراق"],
            ["code" => "IR", "name" => "Iran", "local_name" => "‏ایران"],
            ["code" => "IS", "name" => "Iceland", "local_name" => "Ísland"],
            ["code" => "IT", "name" => "Italy", "local_name" => "Italia"],
            ["code" => "JE", "name" => "Jersey", "local_name" => "Jersey"],
            ["code" => "JM", "name" => "Jamaica", "local_name" => "Jamaica"],
            ["code" => "JO", "name" => "Jordan", "local_name" => "‏الأردن"],
            ["code" => "JP", "name" => "Japan", "local_name" => "日本"],
            ["code" => "KE", "name" => "Kenya", "local_name" => "Kenya"],
            ["code" => "KG", "name" => "Kyrgyzstan", "local_name" => "Кыргызстан"],
            ["code" => "KH", "name" => "Cambodia", "local_name" => "ព្រះរាជាណាចក្រកម្ពុជា"],
            ["code" => "KI", "name" => "Kiribati", "local_name" => "Kiribati"],
            ["code" => "KM", "name" => "Comoros", "local_name" => "‏جزر القمر"],
            ["code" => "KN", "name" => "Saint Kitts and Nevis", "local_name" => "Saint Kitts and Nevis"],
            ["code" => "KP", "name" => "North Korea", "local_name" => "조선 민주주의 인민 공화국"],
            ["code" => "KR", "name" => "South Korea", "local_name" => "대한민국"],
            ["code" => "KW", "name" => "Kuwait", "local_name" => "‏الكويت"],
            ["code" => "KY", "name" => "Cayman Islands", "local_name" => "Cayman Islands"],
            ["code" => "KZ", "name" => "Kazakhstan", "local_name" => "Қазақстан"],
            ["code" => "LA", "name" => "Laos", "local_name" => "ສປປລາວ"],
            ["code" => "LB", "name" => "Lebanon", "local_name" => "‏لبنان"],
            ["code" => "LC", "name" => "Saint Lucia", "local_name" => "Saint Lucia"],
            ["code" => "LI", "name" => "Liechtenstein", "local_name" => "Liechtenstein"],
            ["code" => "LK", "name" => "Sri Lanka", "local_name" => "ශ්‍රී ලංකාව"],
            ["code" => "LR", "name" => "Liberia", "local_name" => "Liberia"],
            ["code" => "LS", "name" => "Lesotho", "local_name" => "Lesotho"],
            ["code" => "LT", "name" => "Lithuania", "local_name" => "Lietuva"],
            ["code" => "LU", "name" => "Luxembourg", "local_name" => "Luxembourg"],
            ["code" => "LV", "name" => "Latvia", "local_name" => "Latvija"],
            ["code" => "LY", "name" => "Libya", "local_name" => "‏ليبيا"],
            ["code" => "MA", "name" => "Morocco", "local_name" => "‏المغرب"],
            ["code" => "MC", "name" => "Monaco", "local_name" => "Monaco"],
            ["code" => "MD", "name" => "Moldova", "local_name" => "Republica Moldova"],
            ["code" => "ME", "name" => "Montenegro", "local_name" => "Crna Gora"],
            ["code" => "MF", "name" => "Saint Martin", "local_name" => "Saint-Martin"],
            ["code" => "MG", "name" => "Madagascar", "local_name" => "Madagascar"],
            ["code" => "MH", "name" => "Marshall Islands", "local_name" => "Marshall Islands"],
            ["code" => "MK", "name" => "Macedonia", "local_name" => "Македонија"],
            ["code" => "ML", "name" => "Mali", "local_name" => "Mali"],
            ["code" => "MM", "name" => "Myanmar", "local_name" => "Myanmar"],
            ["code" => "MN", "name" => "Mongolia", "local_name" => "Монгол улс"],
            ["code" => "MO", "name" => "Macao", "local_name" => "澳門"],
            ["code" => "MP", "name" => "Northern Mariana Islands", "local_name" => "Northern Mariana Islands"],
            ["code" => "MQ", "name" => "Martinique", "local_name" => "Martinique"],
            ["code" => "MR", "name" => "Mauritania", "local_name" => "موريتانيا"],
            ["code" => "MS", "name" => "Montserrat", "local_name" => "Montserrat"],
            ["code" => "MT", "name" => "Malta", "local_name" => "Malta"],
            ["code" => "MU", "name" => "Mauritius", "local_name" => "Maurice"],
            ["code" => "MV", "name" => "Maldives", "local_name" => "Maldives"],
            ["code" => "MW", "name" => "Malawi", "local_name" => "Malawi"],
            ["code" => "MX", "name" => "Mexico", "local_name" => "México"],
            ["code" => "MY", "name" => "Malaysia", "local_name" => "Malaysia"],
            ["code" => "MZ", "name" => "Mozambique", "local_name" => "Moçambique"],
            ["code" => "NA", "name" => "Namibia", "local_name" => "Namibia"],
            ["code" => "NC", "name" => "New Caledonia", "local_name" => "Nouvelle-Calédonie"],
            ["code" => "NE", "name" => "Niger", "local_name" => "Niger"],
            ["code" => "NF", "name" => "Norfolk Island", "local_name" => "Norfolk Island"],
            ["code" => "NG", "name" => "Nigeria", "local_name" => "Nigeria"],
            ["code" => "NI", "name" => "Nicaragua", "local_name" => "Nicaragua"],
            ["code" => "NL", "name" => "Netherlands", "local_name" => "Nederland"],
            ["code" => "NO", "name" => "Norway", "local_name" => "Norge"],
            ["code" => "NP", "name" => "Nepal", "local_name" => "नेपाल"],
            ["code" => "NR", "name" => "Nauru", "local_name" => "Nauru"],
            ["code" => "NU", "name" => "Niue", "local_name" => "Niue"],
            ["code" => "NZ", "name" => "New Zealand", "local_name" => "New Zealand"],
            ["code" => "OM", "name" => "Oman", "local_name" => "‏عُمان"],
            ["code" => "PA", "name" => "Panama", "local_name" => "Panamá"],
            ["code" => "PE", "name" => "Peru", "local_name" => "Perú"],
            ["code" => "PF", "name" => "French Polynesia", "local_name" => "Polynésie française"],
            ["code" => "PG", "name" => "Papua New Guinea", "local_name" => "Papua New Guinea"],
            ["code" => "PH", "name" => "Philippines", "local_name" => "Pilipinas"],
            ["code" => "PK", "name" => "Pakistan", "local_name" => "‏پاکستان"],
            ["code" => "PL", "name" => "Poland", "local_name" => "Polska"],
            ["code" => "PM", "name" => "Saint Pierre and Miquelon", "local_name" => "Saint-Pierre-et-Miquelon"],
            ["code" => "PN", "name" => "Pitcairn Islands", "local_name" => "Pitcairn Islands"],
            ["code" => "PR", "name" => "Puerto Rico", "local_name" => "Puerto Rico"],
            ["code" => "PS", "name" => "Palestine", "local_name" => "‏فلسطين"],
            ["code" => "PT", "name" => "Portugal", "local_name" => "Portugal"],
            ["code" => "PW", "name" => "Palau", "local_name" => "Palau"],
            ["code" => "PY", "name" => "Paraguay", "local_name" => "Paraguay"],
            ["code" => "QA", "name" => "Qatar", "local_name" => "‏قطر"],
            ["code" => "RE", "name" => "Réunion", "local_name" => "La Réunion"],
            ["code" => "RO", "name" => "Romania", "local_name" => "România"],
            ["code" => "RS", "name" => "Serbia", "local_name" => "Србија"],
            ["code" => "RU", "name" => "Russia", "local_name" => "Россия"],
            ["code" => "RW", "name" => "Rwanda", "local_name" => "Rwanda"],
            ["code" => "SA", "name" => "Saudi Arabia", "local_name" => "‏المملكة العربية السعودية"],
            ["code" => "SB", "name" => "Solomon Islands", "local_name" => "Solomon Islands"],
            ["code" => "SC", "name" => "Seychelles", "local_name" => "Seychelles"],
            ["code" => "SD", "name" => "Sudan", "local_name" => "‏السودان"],
            ["code" => "SE", "name" => "Sweden", "local_name" => "Sverige"],
            ["code" => "SG", "name" => "Singapore", "local_name" => "Singapore"],
            ["code" => "SH", "name" => "Saint Helena", "local_name" => "Saint Helena"],
            ["code" => "SI", "name" => "Slovenia", "local_name" => "Slovenija"],
            ["code" => "SJ", "name" => "Svalbard and Jan Mayen", "local_name" => "Svalbard og Jan Mayen"],
            ["code" => "SK", "name" => "Slovakia", "local_name" => "Slovensko"],
            ["code" => "SL", "name" => "Sierra Leone", "local_name" => "Sierra Leone"],
            ["code" => "SM", "name" => "San Marino", "local_name" => "San Marino"],
            ["code" => "SN", "name" => "Senegal", "local_name" => "Sénégal"],
            ["code" => "SO", "name" => "Somalia", "local_name" => "Soomaaliya"],
            ["code" => "SR", "name" => "Suriname", "local_name" => "Suriname"],
            ["code" => "SS", "name" => "South Sudan", "local_name" => "South Sudan"],
            ["code" => "ST", "name" => "São Tomé and Príncipe", "local_name" => "São Tomé e Príncipe"],
            ["code" => "SV", "name" => "El Salvador", "local_name" => "El Salvador"],
            ["code" => "SX", "name" => "Sint Maarten", "local_name" => "Sint Maarten"],
            ["code" => "SY", "name" => "Syria", "local_name" => "‏سوريا"],
            ["code" => "SZ", "name" => "Swaziland", "local_name" => "Swaziland"],
            ["code" => "TC", "name" => "Turks and Caicos Islands", "local_name" => "Turks and Caicos Islands"],
            ["code" => "TD", "name" => "Chad", "local_name" => "Tchad"],
            ["code" => "TF", "name" => "French Southern and Antarctic Lands", "local_name" => "Territoire des Terres australes et antarctiques françaises"],
            ["code" => "TG", "name" => "Togo", "local_name" => "Togo"],
            ["code" => "TH", "name" => "Thailand", "local_name" => "ประเทศไทย"],
            ["code" => "TJ", "name" => "Tajikistan", "local_name" => "Тоҷикистон"],
            ["code" => "TK", "name" => "Tokelau", "local_name" => "Tokelau"],
            ["code" => "TL", "name" => "Timor-Leste", "local_name" => "Timor-Leste"],
            ["code" => "TM", "name" => "Turkmenistan", "local_name" => "Türkmenistan"],
            ["code" => "TN", "name" => "Tunisia", "local_name" => "‏تونس"],
            ["code" => "TO", "name" => "Tonga", "local_name" => "Tonga"],
            ["code" => "TR", "name" => "Turkey", "local_name" => "Türkiye"],
            ["code" => "TT", "name" => "Trinidad and Tobago", "local_name" => "Trinidad and Tobago"],
            ["code" => "TV", "name" => "Tuvalu", "local_name" => "Tuvalu"],
            ["code" => "TW", "name" => "Taiwan", "local_name" => "台灣"],
            ["code" => "TZ", "name" => "Tanzania", "local_name" => "Tanzania"],
            ["code" => "UA", "name" => "Ukraine", "local_name" => "Україна"],
            ["code" => "UG", "name" => "Uganda", "local_name" => "Uganda"],
            ["code" => "UM", "name" => "United States Minor Outlying Islands", "local_name" => "United States Minor Outlying Islands"],
            ["code" => "US", "name" => "United States", "local_name" => "United States"],
            ["code" => "UY", "name" => "Uruguay", "local_name" => "Uruguay"],
            ["code" => "UZ", "name" => "Uzbekistan", "local_name" => "Oʻzbekiston"],
            ["code" => "VA", "name" => "Vatican City", "local_name" => "Vaticano"],
            ["code" => "VC", "name" => "Saint Vincent and the Grenadines", "local_name" => "Saint Vincent and the Grenadines"],
            ["code" => "VE", "name" => "Venezuela", "local_name" => "Venezuela"],
            ["code" => "VG", "name" => "British Virgin Islands", "local_name" => "British Virgin Islands"],
            ["code" => "VI", "name" => "United States Virgin Islands", "local_name" => "United States Virgin Islands"],
            ["code" => "VN", "name" => "Vietnam", "local_name" => "Việt Nam"],
            ["code" => "VU", "name" => "Vanuatu", "local_name" => "Vanuatu"],
            ["code" => "WF", "name" => "Wallis and Futuna", "local_name" => "Wallis et Futuna"],
            ["code" => "WS", "name" => "Samoa", "local_name" => "Samoa"],
            ["code" => "XK", "name" => "Kosovo", "local_name" => "Republika e Kosovës"],
            ["code" => "YE", "name" => "Yemen", "local_name" => "‏اليمن"],
            ["code" => "YT", "name" => "Mayotte", "local_name" => "Mayotte"],
            ["code" => "ZA", "name" => "South Africa", "local_name" => "South Africa"],
            ["code" => "ZM", "name" => "Zambia", "local_name" => "Zambia"],
            ["code" => "ZW", "name" => "Zimbabwe", "local_name" => "Zimbabwe"],
        ];

    }
}
