/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Base: typeof import('./resources/js/Components/Cards/Base.vue')['default']
    BaseButton: typeof import('./resources/js/Components/Buttons/BaseButton.vue')['default']
    BaseLink: typeof import('./resources/js/Components/BaseLink.vue')['default']
    BlocksAmountInfo: typeof import('./resources/js/Components/Elements/BlocksAmountInfo.vue')['default']
    CardAdvance: typeof import('./resources/js/Components/Cards/CardAdvance.vue')['default']
    CheckboxRadio: typeof import('./resources/js/Components/Form/CheckboxRadio.vue')['default']
    DateTimePicker: typeof import('./resources/js/Components/Form/DateTimePicker.vue')['default']
    DropZone: typeof import('./resources/js/Components/Form/DropZone.vue')['default']
    Editor: typeof import('./resources/js/Components/Form/Editor.vue')['default']
    ErrorMessage: typeof import('./resources/js/Components/Partials/ErrorMessage.vue')['default']
    Head: typeof import('@inertiajs/vue3')['Head']
    Icon: typeof import('./resources/js/Components/Icons/Icon.vue')['default']
    IconBorder: typeof import('./resources/js/Components/Icons/IconBorder.vue')['default']
    Info: typeof import('./resources/js/Components/Cards/Partials/Info.vue')['default']
    InputBase: typeof import('./resources/js/Components/Form/InputBase.vue')['default']
    LangDropdown: typeof import('./resources/js/Components/Page/LangDropdown.vue')['default']
    Link: typeof import('@inertiajs/vue3')['Link']
    Mark: typeof import('./resources/js/Components/Cards/Partials/Mark.vue')['default']
    Multiselect: typeof import('./resources/js/Components/Form/Multiselect.vue')['default']
    Price: typeof import('./resources/js/Components/Cards/Partials/Price.vue')['default']
    SelectBase: typeof import('./resources/js/Components/Form/SelectBase.vue')['default']
    Simple: typeof import('./resources/js/Components/Cards/Simple.vue')['default']
    Starts: typeof import('./resources/js/Components/Elements/Starts.vue')['default']
    Switch: typeof import('./resources/js/Components/Form/Switch.vue')['default']
    TagLabel: typeof import('./resources/js/Components/Partials/TagLabel.vue')['default']
    Text: typeof import('./resources/js/Components/Text.vue')['default']
    TextareaBase: typeof import('./resources/js/Components/Form/TextareaBase.vue')['default']
    ToggleModalButton: typeof import('./resources/js/Components/Buttons/ToggleModalButton.vue')['default']
  }
}
