/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./resources/js/Components/Accordion.vue')['default']
    Actions: typeof import('./resources/js/Components/Table/Partials/Actions.vue')['default']
    Avatar: typeof import('./resources/js/Components/Avatar/Avatar.vue')['default']
    BaseButton: typeof import('./resources/js/Components/Buttons/BaseButton.vue')['default']
    BaseInput: typeof import('./resources/js/Components/Form/BaseInput.vue')['default']
    BaseLink: typeof import('./resources/js/Components/BaseLink.vue')['default']
    BaseSelect: typeof import('./resources/js/Components/Form/BaseSelect.vue')['default']
    BaseTable: typeof import('./resources/js/Components/Table/BaseTable.vue')['default']
    BlocksAmountInfo: typeof import('./resources/js/Components/Elements/BlocksAmountInfo.vue')['default']
    Card: typeof import('./resources/js/Components/Cards/Card.vue')['default']
    CardAdvance: typeof import('./resources/js/Components/Cards/CardAdvance.vue')['default']
    CardSimple: typeof import('./resources/js/Components/Cards/CardSimple.vue')['default']
    CheckboxRadio: typeof import('./resources/js/Components/Form/CheckboxRadio.vue')['default']
    Collapse: typeof import('./resources/js/Components/Collapse.vue')['default']
    DateTimePicker: typeof import('./resources/js/Components/Form/DateTimePicker.vue')['default']
    DropZone: typeof import('./resources/js/Components/Upload/DropZone.vue')['default']
    Editor: typeof import('./resources/js/Components/Form/Editor.vue')['default']
    ErrorMessage: typeof import('./resources/js/Components/Partials/ErrorMessage.vue')['default']
    GroupAvatars: typeof import('./resources/js/Components/Avatar/GroupAvatars.vue')['default']
    Head: typeof import('@inertiajs/vue3')['Head']
    Icon: typeof import('./resources/js/Components/Icons/Icon.vue')['default']
    IconBorder: typeof import('./resources/js/Components/Icons/IconBorder.vue')['default']
    Info: typeof import('./resources/js/Components/Cards/Partials/Info.vue')['default']
    LangDropdown: typeof import('./resources/js/Components/General/LangDropdown.vue')['default']
    Line: typeof import('./resources/js/Components/Elements/Line.vue')['default']
    Link: typeof import('@inertiajs/vue3')['Link']
    List: typeof import('./resources/js/Components/List.vue')['default']
    Mark: typeof import('./resources/js/Components/Cards/Partials/Mark.vue')['default']
    MaskInput: typeof import('./resources/js/Components/Form/MaskInput.vue')['default']
    Multiselect: typeof import('./resources/js/Components/Form/Multiselect.vue')['default']
    Pagination: typeof import('./resources/js/Components/Pagination.vue')['default']
    Points: typeof import('./resources/js/Components/Elements/Points.vue')['default']
    Price: typeof import('./resources/js/Components/Cards/Partials/Price.vue')['default']
    ProgressBar: typeof import('./resources/js/Components/Widgets/ProgressBar.vue')['default']
    Starts: typeof import('./resources/js/Components/Elements/Starts.vue')['default']
    Status: typeof import('./resources/js/Components/Table/Partials/Status.vue')['default']
    Switch: typeof import('./resources/js/Components/Form/Switch.vue')['default']
    Tabs: typeof import('./resources/js/Components/Tabs.vue')['default']
    TagLabel: typeof import('./resources/js/Components/Partials/TagLabel.vue')['default']
    Text: typeof import('./resources/js/Components/Text.vue')['default']
    TextareaBase: typeof import('./resources/js/Components/Form/TextareaBase.vue')['default']
    TimeBar: typeof import('./resources/js/Components/Widgets/TimeBar.vue')['default']
    ToggleModalButton: typeof import('./resources/js/Components/Buttons/ToggleModalButton.vue')['default']
    UploadImage: typeof import('./resources/js/Components/Upload/UploadImage.vue')['default']
  }
}
